# Generated by Django 3.1.7 on 2021-03-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('secret_level', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('secret', 'secret'), ('top-secret', 'top-secret'), ('super-secret', 'super-secret')], max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expired', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'active'), ('dead', 'dead')], default='active', max_length=7)),
            ],
        ),
    ]
