# Generated by Django 3.1.7 on 2021-03-31 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210331_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='accounts.dossier'),
        ),
    ]
